environment: development
port: 8081
mysql:
  host: localhost
  port: 3306
  user: root
  password: new-password
  db: cns_backend_test
log:
  level: trace # trace,debug,info,warn,error,fatal,panic
  folder: /Users/dayong/myspace/mywork/cns-backend/.log
rpc:
  url: https://test.confluxrpc.com
  chainID: 1
  privateKeys: ["0x22668895669f3d3a14cf68bcf346b0ed54470075ecb227dc9875bc85c901db44"]
txEngine:
  retryLimit: 10
  sendCountOnce: 500
cnsContracts:
  register: cfxtest:acbrnwph2609zbf21np0501d87xb9dnvuakpv911xk 
  admin: cfxtest:aap8rzfhe7s7ju8ejrp2em4eamr3465y56r4cxb37e