// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/commits": {
            "get": {
                "description": "query commit",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Commits"
                ],
                "summary": "query commit",
                "operationId": "QueryCommit",
                "parameters": [
                    {
                        "type": "string",
                        "name": "order_state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Commit"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    }
                }
            },
            "post": {
                "description": "make commit for record commit detials for using when register",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Commits"
                ],
                "summary": "make commit",
                "operationId": "MakeCommits",
                "parameters": [
                    {
                        "description": "make commit request",
                        "name": "make_commit_req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CommitCore"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.MakeCommitResp"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    }
                }
            }
        },
        "/commits/{commit_hash}": {
            "get": {
                "description": "get commit details by commit hash",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Commits"
                ],
                "summary": "get commit",
                "operationId": "GetCommit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "commit hash",
                        "name": "commit_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Commit"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    }
                }
            }
        },
        "/registers/order/refresh-url/{id}": {
            "put": {
                "description": "refresh register order url",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Registers"
                ],
                "summary": "refresh register order url",
                "operationId": "RefreshRegisterOrderUrl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "commit hash",
                        "name": "commit_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.MakeRegisterOrderResp"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    }
                }
            }
        },
        "/registers/order/{commit_hash}": {
            "get": {
                "description": "make register order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Registers"
                ],
                "summary": "make register order",
                "operationId": "GetRegisterOrder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "commit hash",
                        "name": "commit_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RegisterOrderCore"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    }
                }
            },
            "post": {
                "description": "make register order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Registers"
                ],
                "summary": "make register order",
                "operationId": "MakeRegisterOrder",
                "parameters": [
                    {
                        "description": "make register order request",
                        "name": "make_register_order_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.MakeRegisterOrderReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "commit hash",
                        "name": "commit_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.MakeRegisterOrderResp"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    }
                }
            }
        },
        "/renews/order/refresh-url/{id}": {
            "put": {
                "description": "refresh renew order url",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renews"
                ],
                "summary": "refresh renew order url",
                "operationId": "RefreshRenewOrderUrl",
                "parameters": [
                    {
                        "type": "number",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.MakeRenewOrderResp"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    }
                }
            }
        },
        "/renews/order/{commit_hash}": {
            "get": {
                "description": "make renew order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renews"
                ],
                "summary": "make renew order",
                "operationId": "GetRenewOrder",
                "parameters": [
                    {
                        "type": "number",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RenewOrderCore"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    }
                }
            },
            "post": {
                "description": "make renew order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Renews"
                ],
                "summary": "make renew order",
                "operationId": "MakeRenewOrder",
                "parameters": [
                    {
                        "description": "make renew order request",
                        "name": "make_renew_order_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.MakeRenewOrderReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "commit hash",
                        "name": "commit_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.MakeRenewOrderResp"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/cns_errors.RainbowErrorDetailInfo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cns_errors.RainbowErrorDetailInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "models.Commit": {
            "type": "object",
            "required": [
                "commit_hash"
            ],
            "properties": {
                "commit_hash": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "description": "32字节",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "duration": {
                    "type": "integer"
                },
                "fuses": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "order_state": {
                    "type": "integer"
                },
                "owner": {
                    "description": "base32地址或hex地址",
                    "type": "string"
                },
                "resolver": {
                    "type": "string"
                },
                "reverse_record": {
                    "type": "boolean"
                },
                "secret": {
                    "description": "32字节",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wrapper_expiry": {
                    "type": "integer"
                }
            }
        },
        "models.CommitCore": {
            "type": "object",
            "required": [
                "commit_hash"
            ],
            "properties": {
                "commit_hash": {
                    "type": "string"
                },
                "data": {
                    "description": "32字节",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "duration": {
                    "type": "integer"
                },
                "fuses": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "order_state": {
                    "type": "integer"
                },
                "owner": {
                    "description": "base32地址或hex地址",
                    "type": "string"
                },
                "resolver": {
                    "type": "string"
                },
                "reverse_record": {
                    "type": "boolean"
                },
                "secret": {
                    "description": "32字节",
                    "type": "string"
                },
                "wrapper_expiry": {
                    "type": "integer"
                }
            }
        },
        "models.RegisterOrderCore": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "单位为分",
                    "type": "integer"
                },
                "appName": {
                    "type": "string"
                },
                "code_url": {
                    "type": "string"
                },
                "commit_hash": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "h5_url": {
                    "type": "string"
                },
                "refund_state": {
                    "type": "string"
                },
                "time_expire": {
                    "type": "string"
                },
                "trade_no": {
                    "type": "string"
                },
                "trade_provider": {
                    "type": "string"
                },
                "trade_state": {
                    "type": "string"
                },
                "trade_type": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "tx_state": {
                    "type": "integer"
                }
            }
        },
        "models.RenewOrderCore": {
            "type": "object",
            "required": [
                "cns_name",
                "duration",
                "wrapper_expiry"
            ],
            "properties": {
                "amount": {
                    "description": "单位为分",
                    "type": "integer"
                },
                "appName": {
                    "type": "string"
                },
                "cns_name": {
                    "type": "string"
                },
                "code_url": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "fuses": {
                    "type": "integer"
                },
                "h5_url": {
                    "type": "string"
                },
                "refund_state": {
                    "type": "string"
                },
                "time_expire": {
                    "type": "string"
                },
                "trade_no": {
                    "type": "string"
                },
                "trade_provider": {
                    "type": "string"
                },
                "trade_state": {
                    "type": "string"
                },
                "trade_type": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "tx_state": {
                    "type": "integer"
                },
                "wrapper_expiry": {
                    "type": "integer"
                }
            }
        },
        "services.MakeCommitResp": {
            "type": "object",
            "properties": {
                "commit_hash": {
                    "type": "string"
                }
            }
        },
        "services.MakeRegisterOrderReq": {
            "type": "object",
            "required": [
                "description",
                "trade_type"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "trade_provider": {
                    "type": "string"
                },
                "trade_type": {
                    "type": "string"
                }
            }
        },
        "services.MakeRegisterOrderResp": {
            "type": "object",
            "properties": {
                "code_url": {
                    "type": "string"
                },
                "commit_hash": {
                    "type": "string"
                },
                "h5_url": {
                    "type": "string"
                },
                "trade_no": {
                    "type": "string"
                },
                "trade_provider": {
                    "type": "string"
                },
                "trade_type": {
                    "type": "string"
                }
            }
        },
        "services.MakeRenewOrderReq": {
            "type": "object",
            "required": [
                "cns_name",
                "description",
                "duration",
                "trade_type",
                "wrapper_expiry"
            ],
            "properties": {
                "cns_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "fuses": {
                    "type": "integer"
                },
                "trade_provider": {
                    "type": "string"
                },
                "trade_type": {
                    "type": "string"
                },
                "wrapper_expiry": {
                    "type": "integer"
                }
            }
        },
        "services.MakeRenewOrderResp": {
            "type": "object",
            "properties": {
                "code_url": {
                    "type": "string"
                },
                "h5_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "trade_no": {
                    "type": "string"
                },
                "trade_provider": {
                    "type": "string"
                },
                "trade_type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8081",
	BasePath:         "/v1",
	Schemes:          []string{"http", "https"},
	Title:            "CNS-BACKEND",
	Description:      "The responses of the open api in swagger focus on the data field rather than the code and the message fields",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
